INSERT INTO RESIDUO (TIPO_RESIDUO, DESCRICAO) VALUES ('PLASTICO', 'Embalagens plasticas e PET');
INSERT INTO RESIDUO (TIPO_RESIDUO, DESCRICAO) VALUES ('PAPEL', 'Papeis e cartoes para reciclagem');
INSERT INTO RESIDUO (TIPO_RESIDUO, DESCRICAO) VALUES ('METAL', 'Latas e sucatas metalicas');
INSERT INTO RESIDUO (TIPO_RESIDUO, DESCRICAO) VALUES ('VIDRO', 'Vidro plano e garrafas');
INSERT INTO RESIDUO (TIPO_RESIDUO, DESCRICAO) VALUES ('ORGANICO', 'Residuos organicos para tratamento biologico');
INSERT INTO RESIDUO (TIPO_RESIDUO, DESCRICAO) VALUES ('ELETRONICO', 'Residuos eletroeletronicos para triagem');

INSERT INTO PONTO_COLETA (NOME_PONTO, CAPACIDADE_KG, VOLUME_ALERTA_KG, VOLUME_OCUPADO_KG, STATUS_PONTO, DT_ATUALIZACAO)
VALUES ('Ponto A - Almoxarifado', 1000, 800, 0, 'DISPONIVEL', SYSDATE);

INSERT INTO PONTO_COLETA (NOME_PONTO, CAPACIDADE_KG, VOLUME_ALERTA_KG, VOLUME_OCUPADO_KG, STATUS_PONTO, DT_ATUALIZACAO)
VALUES ('Ponto B - Administrativo', 600, 450, 0, 'DISPONIVEL', SYSDATE);

INSERT INTO PONTO_COLETA (NOME_PONTO, CAPACIDADE_KG, VOLUME_ALERTA_KG, VOLUME_OCUPADO_KG, STATUS_PONTO, DT_ATUALIZACAO)
VALUES ('Ponto C - Producao', 800, 600, 0, 'DISPONIVEL', SYSDATE);

INSERT INTO PONTO_COLETA (NOME_PONTO, CAPACIDADE_KG, VOLUME_ALERTA_KG, VOLUME_OCUPADO_KG, STATUS_PONTO, DT_ATUALIZACAO)
VALUES ('Ponto D - Estacionamento', 1200, 900, 0, 'DISPONIVEL', SYSDATE);

INSERT INTO PONTO_COLETA (NOME_PONTO, CAPACIDADE_KG, VOLUME_ALERTA_KG, VOLUME_OCUPADO_KG, STATUS_PONTO, DT_ATUALIZACAO)
VALUES ('Ponto E - Externo', 500, 350, 0, 'DISPONIVEL', SYSDATE);